'use strict';

const $=selector=>document.querySelector(selector);
const $$=selector=>[...document.querySelectorAll(selector)];
const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const marketOf=symbol=>String(symbol||'').endsWith('.US')?'US':'CN';
const validMarkets=['CN','US'];
const validViews=['today','premarket','holdings','review','strategies','analyze','strategy','system'];
const query=new URLSearchParams(location.search);
let state=null;
const savedMarket=readLocal('shortlist-market','CN');
let currentMarket=validMarkets.includes(query.get('market'))?query.get('market'):(validMarkets.includes(savedMarket)?savedMarket:'CN');
let currentView=validViews.includes(query.get('view'))?query.get('view'):'today';
let holdingKind='real',riskFilter='all',selectedSymbol=null,selectedStrategy='breakout',analysisResult=null,chartBars=[],chartLoadedAt=0,refreshTimer=null;

function readLocal(key,fallback){try{return localStorage.getItem(key)||fallback}catch{return fallback}}
function writeLocal(key,value){try{localStorage.setItem(key,value)}catch{}}
function num(value,digits=2){return value==null||!Number.isFinite(Number(value))?'—':Number(value).toLocaleString('zh-CN',{minimumFractionDigits:digits,maximumFractionDigits:digits})}
function compact(value){if(value==null||!Number.isFinite(Number(value)))return '—';const n=Number(value);return Math.abs(n)>=1e8?`${num(n/1e8)}亿`:Math.abs(n)>=1e4?`${num(n/1e4)}万`:num(n)}
function pct(value){return value==null||!Number.isFinite(Number(value))?'—':`${Number(value)>0?'+':''}${num(value)}%`}
function tone(value){return Number(value)>0?'up':Number(value)<0?'down':''}
function money(value,market=currentMarket){const sign=market==='CN'?'¥':'$';return value==null||!Number.isFinite(Number(value))?'—':`${sign}${num(value)}`}
function source(value){return ({longbridge:'长桥',ibkr:'盈透',lingxi:'灵犀',manual:'手工录入'}[value]||value||'待核验')}
function strategyName(value){return ({breakout:'开盘区间突破',pullback:'首次回调再启动',trend_pullback:'趋势回踩再启动',volatility_breakout:'波动收缩突破'}[value]||value||'等待盘中形态')}
function strategyNames(row){const items=row?.strategies?.length?row.strategies:[row?.strategy];return items.filter(Boolean).map(strategyName).join(' ＋ ')||'等待盘中形态'}
function riskName(value){return ({normal:'普通股',smallcap:'高波动小盘',st:'ST / *ST',pending:'待核验'}[value]||'待核验')}
function time(value,zone='Asia/Shanghai',withDate=true){if(!value)return '时间未提供';try{return new Intl.DateTimeFormat('zh-CN',{timeZone:zone,month:withDate?'2-digit':undefined,day:withDate?'2-digit':undefined,hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).format(new Date(value))}catch{return '时间无效'}}
function dateOnly(value,zone='Asia/Shanghai'){if(!value)return '—';try{return new Intl.DateTimeFormat('zh-CN',{timeZone:zone,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(value))}catch{return '—'}}
function toast(message){const node=$('#toast');node.textContent=message;node.style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>node.style.display='none',4200)}
async function api(path,body){const options=body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json','X-Dashboard-Local':'1'},body:JSON.stringify(body)};const response=await fetch(path,options);let data={};try{data=await response.json()}catch{}if(!response.ok)throw new Error(data.detail||'操作未完成');return data}
async function action(path,body={},message='已完成'){try{await api(path,body);toast(message);await refresh();return true}catch(error){toast(error.message);return false}}
function workspace(){return state?.workspaces?.[currentMarket]}
function updateUrl(){const url=new URL(location.href);url.searchParams.set('market',currentMarket);url.searchParams.set('view',currentView);history.replaceState(null,'',url)}
function showView(view){currentView=validViews.includes(view)?view:'today';$$('.page').forEach(node=>node.classList.toggle('hidden',node.id!==currentView));$$('[data-view]').forEach(node=>node.classList.toggle('active',node.dataset.view===currentView));updateUrl();if(state)renderCurrent()}
function setMarket(market){if(!validMarkets.includes(market))return;currentMarket=market;writeLocal('shortlist-market',market);document.documentElement.dataset.market=market;$$('[data-workspace]').forEach(node=>node.classList.toggle('selected',node.dataset.workspace===market));selectedSymbol=null;chartBars=[];chartLoadedAt=0;updateUrl();if(state)render()}
function scheduleRefresh(){clearTimeout(refreshTimer);refreshTimer=setTimeout(refresh,350)}
async function refresh(){try{state=await api('/api/state');if(!state.workspaces)throw new Error('后台正在更新，请稍后刷新');document.body.classList.remove('disconnected');render()}catch(error){document.body.classList.add('disconnected');$('#market-phase').textContent='本地服务未连接';$('#market-clock').textContent=error.message}}

function render(){const w=workspace();if(!w)return;renderShell(w);renderCurrent()}
function renderCurrent(){if(currentView==='today')renderToday();if(currentView==='premarket')renderPremarket();if(currentView==='holdings')renderHoldings();if(currentView==='review')renderReview();if(currentView==='strategies')renderStrategyCenter();if(currentView==='analyze')renderAnalyze();if(currentView==='strategy')renderStrategy();if(currentView==='system')renderSystem()}
function renderShell(w){
  document.documentElement.dataset.market=currentMarket;
  $('#sidebar-market').textContent=`${w.meta.name}工作区`;
  $$('[data-workspace]').forEach(node=>node.classList.toggle('selected',node.dataset.workspace===currentMarket));
  const ny=time(state.time,'America/New_York',false),cn=time(state.time,'Asia/Shanghai',false);
  $('#market-phase').textContent=`${w.meta.name} · ${w.meta.phase}`;
  $('#market-clock').textContent=currentMarket==='US'?`美东 ${ny} · 北京 ${cn}`:`北京 ${cn} · 基准 ${w.meta.benchmark}`;
  ['today','premarket','holdings','review','strategies','analyze','strategy'].forEach(id=>{const node=$(`#${id}-kicker`);if(node)node.textContent=`${w.meta.name} · ${{today:'今日决策',premarket:'盘前观察',holdings:'持仓管理',review:'复盘研究',strategies:'策略中心',analyze:'单股分析',strategy:'策略说明'}[id]}`});
  $('#lingxi-panel').classList.toggle('hidden',currentMarket!=='CN');
}
function healthStrip(w){const h=w.health;return `<div class="health-item"><span>行情状态</span><b class="health-state ${esc(h.state)}">${esc(h.text)}</b></div><div class="health-item"><span>监测覆盖</span><b>${h.tracked}只 / 已预热${h.ready}只</b></div><div class="health-item"><span>行情截至</span><b>${esc(time(h.data_as_of,w.meta.timezone))}</b></div><div class="health-item"><span>基准与时区</span><b>${esc(w.meta.benchmark)} · ${currentMarket==='CN'?'北京时间':'美东时间'}</b></div>`}

function renderToday(){
  const w=workspace(),d=w.decision,h=w.health;
  $('#health-strip').innerHTML=healthStrip(w);
  const statusText=d.status==='BUY'?'可以买入观察':d.status==='MANAGE'?'先处理持仓':'今天暂不买';
  $('#decision-hero').innerHTML=`<div><span class="kicker">${esc(w.meta.name)} · ${esc(w.meta.phase)}</span><div class="decision-word">${esc(d.headline)}</div><p>${esc(d.reason)}</p></div><span class="decision-mark ${d.status==='MANAGE'?'manage':''}">${statusText}</span>`;
  $('#primary-decision').innerHTML=d.primary?primaryCard(d.primary,w):emptyPrimary(d,w);
  const slots=[...d.backups.map(row=>({...row,slotType:'buy'})),...d.watching.filter(row=>!d.backups.some(item=>item.symbol===row.symbol)).map(row=>({...row,slotType:'watch'}))].slice(0,2);
  while(slots.length<2)slots.push(null);
  $('#backup-decisions').innerHTML=slots.map((row,index)=>row?backupCard(row,index+1):`<div class="empty-backup"><b>备选 ${index+1} · 暂无</b><p>还没有更多股票通过盘前筛选与风险约束。</p></div>`).join('');
  const actions=w.holdings.actionable.filter(row=>row.holding_type==='real');
  $('#holding-actions').innerHTML=actions.length?actions.slice(0,4).map(holdingActionRow).join(''):`<div class="empty">当前没有需要立即处理的真实持仓。<br><small>${w.holdings.real.length?`本市场共${w.holdings.real.length}只真实持仓，完整列表在持仓管理。`:'尚未录入或同步本市场真实持仓。'}</small></div>`;
  const reasons=[...h.issues,d.reason];if(!d.primary&&d.watching[0])reasons.push(`${d.watching[0].name}：${d.watching[0].reason}`);
  $('#waiting-reasons').innerHTML=[...new Set(reasons.filter(Boolean))].slice(0,4).map((reason,index)=>`<div class="list-row"><div><b>${index===0?'当前结论':'仍需满足'}</b></div><div>${esc(reason)}</div><span class="action-chip">等待</span></div>`).join('')||'<div class="empty">当前条件完整。</div>';
  $('#market-alerts').innerHTML=w.alerts.length?w.alerts.slice(0,6).map(alertRow).join(''):'<div class="empty">当前市场暂无提醒。</div>';
}
function emptyPrimary(d,w){return `<div class="empty-primary"><div><div class="empty-icon">○</div><h2>${esc(d.headline)}</h2><p>${esc(d.reason)}。盘前名单仍会继续观察，但不会为了填满推荐位而显示买入。</p><button class="secondary" data-go="premarket">查看${esc(w.meta.name)}观察名单</button></div></div>`}
function primaryCard(row,w){const price=row.current_price??row.price;return `<article class="decision-card primary-card"><div class="card-top"><div class="stock-title"><span class="kicker">综合首选 · ${esc(strategyNames(row))}</span><h2>${esc(row.name||row.symbol)}</h2><small>${esc(row.symbol)} · ${esc(riskName(row.risk_group))}</small></div><span class="verdict">可考虑买入</span></div><div class="live-price">${money(price)} <small class="quote-time">行情 ${esc(time(row.quote_time,w.meta.timezone))}</small></div><div class="entry-band"><div><span>买入区间</span><b>${money(row.entry_min)}–${money(row.entry_max)}</b></div><div><span>不追价上限</span><b>${money(row.entry_max)}</b></div></div><div class="level-grid"><div><span>初始止损</span><b>${money(row.stop)}</b></div><div><span>第一止盈</span><b>${money(row.target)}</b></div><div><span>建议数量</span><b>${num(row.qty,0)}股</b></div><div><span>占用资金</span><b>${money(row.cash_required)}</b></div><div><span>计划风险</span><b>${money(row.planned_risk)}</b></div><div><span>风险距离</span><b>${money(row.price_risk)}</b></div><div><span>信号失效</span><b>${esc(time(row.valid_until,w.meta.timezone))}</b></div><div><span>最早可卖</span><b>${esc(row.earliest_sell||'—')}</b></div></div><div class="exit-rule"><b>余仓退出：</b>首次止盈后，以随后完整3根5分钟K线低点的最低值上移保护，最迟第三个交易日退出。</div><div class="card-foot"><span>${esc(row.reason)}</span><span>${esc(source(row.source))} · ${esc(row.version||state.version)}</span></div></article>`}
function backupCard(row,index){const buy=row.slotType==='buy';const price=row.current_price??row.price??row.quote?.price;return `<article class="decision-card backup-card"><div class="card-top"><div><span class="kicker">备选 ${index} · ${buy?'已通过执行检查':'观察备选'}</span><h3>${esc(row.name||row.symbol)} <small>${esc(row.symbol)}</small></h3></div><span class="state-chip ${buy?'buy':''}">${buy?'可考虑买入':'继续观察'}</span></div><p>${esc(row.reason||'等待盘中确认')}</p><div class="backup-levels"><div>现价<b>${money(price)}</b></div><div>${buy?'买入区间':'突破观察位'}<b>${buy?`${money(row.entry_min)}–${money(row.entry_max)}`:money(row.trigger)}</b></div><div>保护参考<b>${money(row.stop)}</b></div></div></article>`}
function holdingActionRow(row){return `<div class="list-row"><div><b>${esc(row.name||row.symbol)}</b><small>${esc(row.symbol)} · ${row.holding_type==='real'?'真实持仓':'模拟持仓'}</small></div><div>${esc(row.reason||'等待条件')}<small>价格 ${money(row.price,marketOf(row.symbol))} · 保护 ${money(row.stop,marketOf(row.symbol))}</small></div><span class="action-chip ${row.event?'urgent':''}">${esc(row.action||'继续持有')}</span></div>`}
function alertRow(row){return `<div class="alert-row ${row.read?'read':''}"><time>${esc(time(row.time,workspace().meta.timezone))}</time><b>${esc(row.title)}</b><span>${esc(row.message)}</span>${row.read?'':`<button class="text-button" data-alert-read="${esc(row.id)}">标为已读</button>`}</div>`}

function renderPremarket(){
  const w=workspace(),rows=w.premarket.filter(row=>{const q=$('#premarket-search').value.trim().toUpperCase();return (!q||row.symbol.includes(q)||String(row.name).toUpperCase().includes(q))&&(riskFilter==='all'||row.risk_group===riskFilter)});
  $('#premarket-summary').innerHTML=`<div class="health-item"><span>下个观察日</span><b>${esc(w.premarket[0]?.trade_date||'待交易日历确认')}</b></div><div class="health-item"><span>盘前名单</span><b>${w.premarket.length}只</b></div><div class="health-item"><span>已纳入盯盘</span><b>${w.premarket.filter(row=>row.monitored).length}只</b></div><div class="health-item"><span>筛选更新时间</span><b>${esc(time(state.selection_updated,w.meta.timezone))}</b></div>`;
  $('#refresh-premarket').disabled=Boolean(state.selection_running||state.scanning);$('#refresh-premarket').textContent=state.selection_running?`整理中 ${state.selection_progress.done}/${state.selection_progress.total}`:state.scanning?'更新候选中…':'更新盘前筛选';
  $('#premarket-count').textContent=`显示 ${rows.length} / ${w.premarket.length}`;
  if(!rows.some(row=>row.symbol===selectedSymbol)){selectedSymbol=rows[0]?.symbol||null;chartBars=[];chartLoadedAt=0}
  $('#premarket-rows').innerHTML=rows.length?rows.map(row=>`<tr data-symbol="${esc(row.symbol)}" class="${row.symbol===selectedSymbol?'selected':''}"><td><div class="symbol-cell"><span class="rank">${row.rank}</span><div><b>${esc(row.name)}</b><small>${esc(row.symbol)}</small></div></div></td><td><span class="score">${num(row.score,0)}</span></td><td>${money(row.close)}</td><td>${money(row.breakout_reference)}</td><td>${money(row.structure_low)}</td><td>${compact(row.average_turnover)}</td><td class="${tone(row.distance_to_high_pct)}">${pct(row.distance_to_high_pct)}</td><td><span class="risk-chip ${esc(row.risk_group)}">${esc(riskName(row.risk_group))}</span></td><td class="wait-cell">${esc(row.reason)}</td></tr>`).join(''):'<tr><td colspan="9"><div class="empty">没有符合当前筛选的盘前股票。</div></td></tr>';
  renderStockDetail();renderBreadth();
  if(selectedSymbol&&Date.now()-chartLoadedAt>15000)loadChart(selectedSymbol);
}
async function loadChart(symbol){const row=workspace().premarket.find(item=>item.symbol===symbol);chartLoadedAt=Date.now();try{const bars=await api(`/api/bars/${encodeURIComponent(symbol)}?source=${encodeURIComponent(row?.source||'longbridge')}`);if(symbol===selectedSymbol){chartBars=bars;renderStockDetail()}}catch{if(symbol===selectedSymbol){chartBars=[];renderStockDetail()}}}
function renderStockDetail(){const w=workspace(),row=w.premarket.find(item=>item.symbol===selectedSymbol);if(!row){$('#stock-detail').innerHTML='<div class="empty">选择一只股票查看完整依据。</div>';return}const candidate=w.candidates.find(item=>item.symbol===row.symbol),q=candidate?.quote,price=q?.price??row.close,change=q?.change_pct,dataTime=q?.market_time?time(q.market_time,w.meta.timezone):row.as_of||'日期未提供';$('#stock-detail').innerHTML=`<div class="detail-header"><span class="kicker">排名 ${row.rank} · ${esc(riskName(row.risk_group))}</span><h2>${esc(row.name)}</h2><small>${esc(row.symbol)}</small><div class="detail-price">${money(price)} <small class="${tone(change)}">${pct(change)}</small></div><div class="detail-meta">${q?'当前报价':'最近完整日线收盘'} · ${esc(source(q?.source||row.source))}<br>数据时间 ${esc(dataTime)}</div></div><div class="chart">${chart(chartBars,w.meta.timezone)}</div><div class="detail-body"><div class="detail-row"><span>20日均线</span><b>${money(row.ma20)}</b></div><div class="detail-row"><span>20日相对强弱</span><b>${pct(row.relative_strength)}</b></div><div class="detail-row"><span>平均成交额</span><b>${compact(row.average_turnover)}</b></div><div class="detail-row"><span>日线量比</span><b>${num(row.volume_ratio)}倍</b></div><div class="detail-row"><span>ATR / 价格</span><b>${pct(row.atr_pct)}</b></div><div class="detail-note"><b>等待条件：</b>${esc(row.reason)}<br>观察位不是买入价，仍需盘中完整5分钟K线确认。</div><div class="detail-actions"><button class="secondary" data-watch="${esc(row.symbol)}" data-remove="${row.monitored?'1':'0'}">${row.monitored?'移出监测':'加入监测'}</button></div></div>`}
function chart(bars,zone){if(!bars.length)return '<div class="empty">5分钟K线尚未就绪<br><small>不会用示例图代替真实行情</small></div>';const data=bars.slice(-50),width=360,height=155,pad=20,low=Math.min(...data.map(row=>row.low)),high=Math.max(...data.map(row=>row.high)),range=high-low||1,x=index=>pad+index*(width-pad*2)/data.length,y=value=>12+(high-value)/range*(height-35);let svg=`<svg viewBox="0 0 ${width} ${height}" role="img" aria-label="最近完整5分钟K线">`;for(let index=0;index<3;index++){const value=low+range*index/2;svg+=`<line x1="16" x2="344" y1="${y(value)}" y2="${y(value)}" stroke="#e7eae4"/><text class="chart-label" x="18" y="${y(value)-4}">${num(value)}</text>`}const barWidth=Math.max(1.6,(width-pad*2)/data.length*.58);data.forEach((row,index)=>{const color=row.close>=row.open?'#b34a3e':'#2e7a59';svg+=`<line x1="${x(index)}" x2="${x(index)}" y1="${y(row.high)}" y2="${y(row.low)}" stroke="${color}"/><rect x="${x(index)-barWidth/2}" y="${Math.min(y(row.open),y(row.close))}" width="${barWidth}" height="${Math.max(1,Math.abs(y(row.open)-y(row.close)))}" fill="${color}"/>`});return svg+`<text class="chart-label" x="18" y="153">${esc(time(data[0].start,zone))}</text><text class="chart-label" x="342" y="153" text-anchor="end">5分钟 · ${esc(source(data[0].source))}</text></svg>`}
function renderBreadth(){const w=workspace(),b=w.breadth;$('#breadth-title').textContent=currentMarket==='CN'?'A股市场广度':'美股市场广度';if(!b.available){$('#market-breadth').innerHTML=`<div class="empty">${esc(b.message||'当前市场广度未接入')}，不会复用另一市场的统计。</div>`;return}$('#market-breadth').innerHTML=`<div class="breadth-grid"><div><span>上涨家数</span><b class="up">${num(b.up_count,0)}</b></div><div><span>下跌家数</span><b class="down">${num(b.down_count,0)}</b></div><div><span>涨停家数</span><b>${num(b.up_limit_count,0)}</b></div><div><span>跌停家数</span><b>${num(b.down_limit_count,0)}</b></div></div>`}

function renderHoldings(){
  const w=workspace(),real=w.holdings.real,paper=w.holdings.paper;
  $('#holding-summary').innerHTML=`<div class="health-item"><span>真实持仓</span><b>${real.length}只</b></div><div class="health-item"><span>模拟持仓</span><b>${paper.length}只</b></div><div class="health-item"><span>需处理动作</span><b>${w.holdings.actionable.length}项</b></div><div class="health-item"><span>未纳入监测</span><b>${w.health.uncovered_holdings}只</b></div>`;
  $$('[data-holding-kind]').forEach(node=>node.classList.toggle('selected',node.dataset.holdingKind===holdingKind));
  const rows=holdingKind==='real'?real:paper;
  if(!rows.length){$('#holdings-content').innerHTML=`<div class="empty">本市场暂无${holdingKind==='real'?'真实':'模拟'}持仓。</div>`;return}
  if(holdingKind==='real')$('#holdings-content').innerHTML=`<table class="holdings-table"><thead><tr><th>股票 / 来源</th><th>现价</th><th>成本</th><th>浮动盈亏</th><th>保护价</th><th>止盈价</th><th>当前动作</th><th>行情时间</th><th></th></tr></thead><tbody>${rows.map(row=>`<tr><td><b>${esc(row.name||row.symbol)}</b><small>${esc(row.symbol)} · ${esc(source(row.source))}</small></td><td>${money(row.price)}</td><td>${money(row.cost)}</td><td class="pnl ${tone(row.unrealized_pnl)}">${money(row.unrealized_pnl)}<small>${pct(row.unrealized_pct)}</small></td><td>${money(row.stop)}</td><td>${money(row.target)}</td><td><span class="action-chip ${row.event?'urgent':''}">${esc(row.action)}</span><small>${esc(row.reason)}</small></td><td>${esc(time(row.quote_time,w.meta.timezone))}</td><td><button class="row-action" data-edit-holding="${esc(row.id)}">编辑计划</button></td></tr>`).join('')}</tbody></table>`;
  else $('#holdings-content').innerHTML=`<table class="holdings-table"><thead><tr><th>股票 / 策略</th><th>现价</th><th>买入价</th><th>剩余数量</th><th>保护价</th><th>第一止盈</th><th>当前动作</th><th>行情时间</th></tr></thead><tbody>${rows.map(row=>`<tr><td><b>${esc(row.name||row.symbol)}</b><small>${esc(row.symbol)} · ${esc(strategyName(row.strategy))}</small></td><td>${money(row.price)}</td><td>${money(row.entry)}</td><td>${num(row.remaining,0)}股</td><td>${money(row.stop)}</td><td>${money(row.target)}</td><td><span class="action-chip ${row.event?'urgent':''}">${esc(row.action)}</span><small>${esc(row.reason)}</small></td><td>${esc(time(row.quote_time,w.meta.timezone))}</td></tr>`).join('')}</tbody></table>`;
}
function openHolding(row=null){const dialog=$('#holding-dialog'),synced=row&&row.source!=='manual';$('#holding-dialog-title').textContent=row?'编辑退出计划':'手工录入';$('#holding-id').value=row?.id||'';$('#holding-source').value=row?.source||'manual';$('#holding-symbol').value=row?.symbol||'';$('#holding-name').value=row?.name||'';$('#holding-quantity').value=row?.quantity??'';$('#holding-cost').value=row?.cost??'';$('#holding-date').value=row?.entry_date||'';$('#holding-stop').value=row?.stop??'';$('#holding-target').value=row?.target??'';$('#holding-note').value=row?.note||'';['holding-symbol','holding-name','holding-quantity','holding-cost'].forEach(id=>{$(`#${id}`).disabled=Boolean(synced)});$('#remove-holding').classList.toggle('hidden',!row||row.source!=='manual');dialog.showModal()}

function renderReview(){const w=workspace(),a=w.simulation;$('#toggle-simulation').textContent=state.settings.simulation_enabled?'暂停模拟新开仓':'恢复模拟新开仓';$('#review-account').innerHTML=`<section class="account-card"><div><span>${esc(w.meta.name)}模拟账户权益</span><strong>${money(a.equity)}</strong></div><div><span>账户收益</span><strong class="${tone(a.return_pct)}">${pct(a.return_pct)}</strong></div><div><span>最大回撤</span><strong>${pct(-a.max_drawdown)}</strong></div><div><span>可用现金</span><strong>${money(a.cash)}</strong></div></section>`;$('#strategy-metrics').innerHTML=`<div class="metric-list">${Object.entries(a.strategies).map(([key,row])=>`<div class="metric"><div><b>${esc(strategyName(key))}</b><small>${row.enough?'已达到首次比较样本':'样本不足30笔'}</small></div><div>结束<b>${row.count}</b></div><div>净盈亏<b class="${tone(row.net_pnl)}">${money(row.net_pnl)}</b></div><div>胜率<b>${row.win_rate==null?'—':pct(row.win_rate*100)}</b></div><div>最长连亏<b>${row.loss_streak}</b></div><div>成本加倍<b>${money(row.double_cost_pnl)}</b></div></div>`).join('')}</div>`;const failures=state.failures.filter(row=>marketOf(row.symbol)===currentMarket).slice(-12).reverse();$('#market-failures').innerHTML=failures.length?failures.map(row=>`<div class="event-row"><time>${esc(time(row.time,w.meta.timezone))}</time><b>${esc(row.symbol)}</b><span>${esc(row.reason)}</span></div>`).join(''):'<div class="empty">本市场暂无未成交或取消记录。</div>';$('#market-trades').innerHTML=tradeTable(a.trades,w);const select=$('#replay-symbol');if(select){const old=select.value;select.innerHTML=state.watch.filter(symbol=>marketOf(symbol)===currentMarket).map(symbol=>`<option>${esc(symbol)}</option>`).join('');if([...select.options].some(option=>option.value===old))select.value=old}}
function tradeTable(rows,w){if(!rows.length)return '<div class="empty">暂无已结束交易，继续积累前向样本。</div>';return `<div class="table-wrap"><table><thead><tr><th>股票</th><th>策略 / 分类</th><th>买入时间</th><th>退出时间</th><th>净盈亏</th><th>持有交易日</th></tr></thead><tbody>${rows.slice(-40).reverse().map(row=>`<tr><td>${esc(row.symbol)}</td><td>${esc(strategyName(row.strategy))}<small>${esc(riskName(row.risk_group))}</small></td><td>${esc(time(row.entry_time,w.meta.timezone))}</td><td>${esc(time(row.exit_time,w.meta.timezone))}</td><td class="${tone(row.net_pnl)}">${money(row.net_pnl)}</td><td>${num(row.holding_sessions,0)}</td></tr>`).join('')}</tbody></table></div>`}

function renderStrategyCenter(){
  const w=workspace(),items=w.strategies||[];if(!items.length)return;
  if(!items.some(row=>row.strategy===selectedStrategy))selectedStrategy=items[0].strategy;
  $('#strategy-cards').innerHTML=items.map(row=>`<button class="strategy-summary ${row.strategy===selectedStrategy?'selected':''}" data-select-strategy="${esc(row.strategy)}"><span class="kicker">${esc(row.category)} · ${row.enabled?'运行中':'已停用'}</span><h2>${esc(row.name)}</h2><p>${esc(row.summary)}</p><div><b>${row.forward_count}</b><small>结束样本</small><b>${row.performance?.net_pnl==null?'—':money(row.performance.net_pnl)}</b><small>净盈亏</small></div><i class="${row.enabled?'on':''}"></i></button>`).join('');
  const row=items.find(item=>item.strategy===selectedStrategy),rec=w.strategy_recommendations?.[selectedStrategy]||{rows:[]};
  const candidates=rec.rows?.length?rec.rows.map((candidate,index)=>strategyCandidate(candidate,index)).join(''):'<div class="empty">当前没有符合该策略盘前条件的股票。</div>';
  const waiting=rec.waiting?.length?`<div class="strategy-waiting"><b>继续等待</b><p>${rec.waiting.map(item=>`${esc(item.name||item.symbol)}：${esc(item.reason)}`).join('<br>')}</p></div>`:'';
  $('#strategy-workbench').innerHTML=`<div class="strategy-head"><div><span class="kicker">${esc(w.meta.name)} · ${esc(row.category)}</span><h2>${esc(row.name)}</h2><p>${esc(row.summary)}</p></div><div class="title-actions"><button class="secondary" data-show-versions="${esc(row.strategy)}">版本记录</button><button class="${row.enabled?'danger-button':'primary'}" data-strategy-toggle="${esc(row.strategy)}" data-enabled="${row.enabled?'0':'1'}">${row.enabled?'停用策略':'启用策略'}</button></div></div><div class="strategy-columns"><section><div class="section-label"><b>该策略今日名单</b><span>首选1只 · 备选2只</span></div><div class="strategy-candidates">${candidates}${waiting}</div></section><section><div class="section-label"><b>当前参数</b><span>保存后立即生成新版本</span></div><form id="strategy-config-form" data-strategy-id="${esc(row.strategy)}"><div class="parameter-grid">${row.fields.map(field=>`<label>${esc(field.label)}<input data-param="${esc(field.key)}" type="number" value="${esc(field.value)}" min="${esc(field.min)}" max="${esc(field.max)}" step="${field.type==='int'?'1':'any'}"><small>${num(field.min)}–${compact(field.max)}</small></label>`).join('')}</div><label class="change-reason">修改说明<input id="strategy-change-reason" maxlength="200" placeholder="例如：降低成交量门槛做观察实验"></label><button class="primary">保存并立即生效</button><p class="form-hint">新版本会取消该策略旧待买信号；已有持仓的保护计划不变，前向样本重新累计。</p></form></section></div>`;
}
function strategyCandidate(row,index){const conditions=Object.entries(row.conditions||{});return `<article class="strategy-pick"><div class="card-top"><div><span class="kicker">${index===0?'策略首选':`备选 ${index}`}</span><h3>${esc(row.name||row.symbol)}</h3><small>${esc(row.symbol)} · ${esc(riskName(row.risk_group))}</small></div><span class="state-chip ${row.state==='buy'?'buy':''}">${row.state==='buy'?'可考虑买入':'继续观察'}</span></div><p>${esc(row.reason)}</p><div class="pick-levels"><span>准备度<b>${num(row.score,0)}</b></span><span>观察位<b>${money(row.trigger)}</b></span><span>保护参考<b>${money(row.stop)}</b></span></div><div class="condition-chips">${conditions.map(([key,value])=>`<span class="${value?'pass':'wait'}">${value?'✓':'○'} ${esc(key)}</span>`).join('')}</div></article>`}

function renderAnalyze(){if(analysisResult&&analysisResult.market===currentMarket)$('#analyze-result').innerHTML=analysisHtml(analysisResult)}
function analysisHtml(result){const w=workspace(),q=result.quote,final=result.final;return `<section class="analysis-hero ${String(final.status).toLowerCase()}"><div><span class="kicker">${esc(result.name)} · ${esc(result.symbol)}</span><h2>${esc(final.action)}</h2><p>${esc(final.reason)}</p></div><div class="analysis-price"><b>${money(q?.price)}</b><small>${q?esc(time(q.market_time,w.meta.timezone)):'行情未通过核验'}</small></div></section><div class="analysis-actions"><button class="secondary" data-analysis-monitor="${esc(result.symbol)}">${result.monitored?'已在持续监测':'＋ 加入盘中监测'}</button>${result.holding_origin==='saved'?'<span class="action-chip">已结合已保存或同步持仓</span>':'<button class="secondary" data-analysis-save-holding="1">保存为真实持仓</button>'}</div>${holdingAnalysis(result.holding)}<div class="analysis-strategies">${result.strategies.map(row=>`<article class="panel analysis-strategy"><div class="panel-head"><div><span class="kicker">${esc(row.version)}</span><h2>${esc(row.name)}</h2></div><span class="state-chip ${row.state==='符合'?'buy':''}">${esc(row.state)}</span></div><div class="analysis-body"><p>${esc(row.reason)}</p>${analysisLevels(row)}<div class="condition-list">${Object.entries(row.conditions||{}).filter(([,value])=>typeof value==='boolean').map(([key,value])=>`<div><span>${esc(key)}</span><b class="${value?'up':'muted'}">${value?'通过':'等待'}</b></div>`).join('')}</div></div></article>`).join('')}</div><p class="analysis-note">${esc(result.note)} · 来源：${esc(source(result.source))}</p>`}
function holdingAnalysis(row){if(!row)return '';return `<section class="panel analysis-holding"><div class="panel-head"><div><span class="kicker">真实持仓处理</span><h2>${esc(row.action)}</h2></div><span class="state-chip ${row.event?'urgent':''}">${num(row.quantity,0)}股</span></div><div class="analysis-levels"><span>现价<b>${money(row.price)}</b></span><span>买入均价<b>${money(row.cost)}</b></span><span>浮动盈亏<b class="${tone(row.unrealized_pnl)}">${money(row.unrealized_pnl)}</b></span><span>保护 / 止盈<b>${money(row.stop)} / ${money(row.target)}</b></span></div><p>${esc(row.reason)}</p></section>`}
function analysisLevels(row){const d=row.decision,c=row.conditions||{};if(d)return `<div class="analysis-levels"><span>买入区间<b>${money(d.entry_min)}–${money(d.entry_max)}</b></span><span>止损<b>${money(d.stop)}</b></span><span>第一止盈<b>${money(d.target)}</b></span><span>建议数量<b>${num(d.qty,0)}股</b></span></div>`;return `<div class="analysis-levels"><span>观察位<b>${money(c.level)}</b></span><span>保护参考<b>${money(c.stop)}</b></span><span>相对量能<b>${c.relative_volume==null?'—':num(c.relative_volume)+'倍'}</b></span><span>状态<b>${c.ready?'已具备数据':'继续补数据'}</b></span></div>`}

function renderStrategy(){const w=workspace(),cn=currentMarket==='CN';$('#strategy-content').innerHTML=`<div class="strategy-flow"><article class="flow-step"><span>01 · 盘前</span><h3>趋势与流动性</h3><p>20日均线上行，20日收益强于${esc(w.meta.benchmark)}，平均成交额不少于${cn?'1亿元':'500万美元'}。</p></article><article class="flow-step"><span>02 · 开盘</span><h3>建立观察区间</h3><p>${cn?'取开盘15分钟区间，最早9:50确认':'取开盘5分钟区间，最早9:40确认'}。</p></article><article class="flow-step"><span>03 · 买点</span><h3>完整K线确认</h3><p>突破或首次回调再启动，并同时站上当日近似VWAP与通过市场过滤。</p></article><article class="flow-step"><span>04 · 执行</span><h3>价格与盘口</h3><p>报价30秒内、买卖盘15秒内，不超过不追价上限，再计算数量和资金。</p></article><article class="flow-step"><span>05 · 退出</span><h3>先计划后买入</h3><p>初始止损、2倍风险减半、余仓跟踪，最迟第三个交易日退出。</p></article></div><div class="two-columns"><section class="panel rule-card"><h2>${esc(w.meta.name)}买入规则</h2><ul><li>突破型：完整5分钟K线收盘突破开盘区间高点，站上VWAP，同时间成交活跃度至少1.5倍。</li><li>回调型：突破后6根K线内首次回踩，0.3%容差内守住突破位，随后收盘突破上一根高点。</li><li>趋势回踩：日线MA20高于MA60，盘中回踩VWAP或EMA20后放量转强。</li><li>波动收缩：ATR5/ATR20不超过0.75并靠近20日高点，随后放量突破10日整理区。</li><li>已有真实持仓、过期报价、盘口缺失、追价过高、资金或高风险名额不足时不进入首选。</li><li>每笔计划风险0.25%，每市场最多3只持仓，高风险合计最多1只。</li></ul></section><section class="panel rule-card"><h2>${esc(w.meta.name)}退出规则</h2><ul><li>突破型止损取信号K线及此前3根低点；回调型取已确认回调低点。</li><li>达到两倍初始价格风险时减半；余仓保护价只会上移。</li><li>${cn?'A股新买股份当日不可卖；触及条件只记录待退出，不能假设成交。':'美股没有A股T+1限制，但止损触价仍需有效盘口确认。'}</li><li>跳空、停牌、涨跌停或流动性不足时，计划亏损可能小于实际亏损。</li></ul></section></div><section class="panel rule-card"><h2>如何理解页面结论</h2><ul><li><b>可考虑买入：</b>盘前、盘中、行情、盘口与资金全部通过，且信号仍在有效期。</li><li><b>观察备选：</b>趋势或形态值得盯，但仍缺少一个或多个买入条件。</li><li><b>今天暂不买：</b>没有股票满足全部条件，空缺位置不会用低质量候选补满。</li><li>这些参数是本地实验值，真实交易由你决定，系统不提供真实下单入口。</li></ul></section>`}

function renderSystem(){
  const descriptions={longbridge:'持续行情、候选筛选与历史K线。App内可见行情不等于接口权限，按市场逐项核验。',ibkr:'美股行情核验、历史补充与备用。通过本机TWS或Gateway只读连接。',lingxi:'A股榜单、行情查询和自然语言筛选补充；未验证持续推送前不作为主源。'};
  $('#provider-cards').innerHTML=Object.entries(state.providers).map(([id,row])=>`<article class="panel provider"><h2>${esc(source(id))}<span class="action-chip ${row.state==='connected'?'':'urgent'}">${row.state==='connected'?'已接通':'待连接'}</span></h2><p>${esc(descriptions[id])}</p><small>${esc(row.message||'等待检查')}</small><small>最近成功 ${esc(time(row.last_ok))}${row.latency_ms!=null?` · 请求 ${num(row.latency_ms,0)}ms`:''}</small>${row.market_access?`<div class="provider-access">${Object.entries(row.market_access).map(([market,access])=>`<small><b>${esc(market)}</b> · 报价${access.quote?'已验证':'待验证'} · 买卖盘${access.depth?'已验证':'待验证'} · 推送${access.subscription?'已验证':'待验证'}</small>`).join('')}</div>`:''}<button class="secondary" data-connect="${id}">${id==='longbridge'?'检查长桥权限':id==='ibkr'?'连接盈透本地接口':'检查灵犀'}</button>${row.auth_url?`<a class="text-button" target="_blank" rel="noreferrer" href="${esc(row.auth_url)}">打开长桥授权页</a>`:''}</article>`).join('')+`<article class="panel provider"><h2>同花顺<span class="action-chip">人工入口</span></h2><p>普通手机或电脑客户端用于人工看盘和核对。目前不作为程序行情源。</p><small>以后取得正式数据接口权限，再作为独立数据源接入。</small></article>`;
  renderNotifications();if(document.activeElement!==$('#monitor-limit'))$('#monitor-limit').value=state.settings.monitor_limit;if(document.activeElement!==$('#ib-port'))$('#ib-port').value=state.settings.ib_port;$('#monitor-toggle').textContent=state.monitor.running?'暂停盯盘':'恢复盯盘';$('#benchmarks').innerHTML=state.benchmarks.length?state.benchmarks.slice(0,14).map(row=>`<div class="event-row"><time>${esc(time(row.time))}</time><b>${esc(source(row.source))}</b><span>${row.operation?esc(row.operation):`请求 ${num(row.request_ms,0)}ms · 返回 ${row.returned}/${row.requested}个样本${row.during_session?'':' · 休市样本'}`}</span></div>`).join(''):'<div class="empty">暂无连接检查记录。</div>';$('#system-events').innerHTML=state.events.length?state.events.slice(0,24).map(row=>`<div class="event-row"><time>${esc(time(row.time))}</time><b>${esc(row.symbol||'系统')}</b><span>${esc(row.message)}</span></div>`).join(''):'<div class="empty">暂无异常记录。</div>';
}
function renderNotifications(){const n=state.notification_settings,permission=({authorized:'已授权',provisional:'临时授权',denied:'已拒绝',not_determined:'尚未选择',unknown:'检查中',unavailable:'不可用'}[n.permission]||n.permission);$('#notification-settings').innerHTML=`<div class="toggle-row"><span>看板提醒</span><input type="checkbox" id="notify-enabled" ${n.enabled?'checked':''}></div><div class="toggle-row"><span>Mac通知中心</span><input type="checkbox" id="notify-desktop" ${n.desktop?'checked':''}></div><div class="toggle-row"><span>触发提示音</span><input type="checkbox" id="notify-sound" ${n.sound?'checked':''}></div><div class="toggle-row"><span>系统权限</span><b>${esc(permission||'检查中')}</b></div><div class="toggle-row"><button class="secondary" id="save-notifications">保存提醒设置</button><button class="text-button" id="test-notification">测试Mac通知</button></div>`}

function bindEvents(){
  document.addEventListener('click',async event=>{
    const workspaceButton=event.target.closest('[data-workspace]');if(workspaceButton){setMarket(workspaceButton.dataset.workspace);return}
    const viewButton=event.target.closest('[data-view]');if(viewButton){showView(viewButton.dataset.view);return}
    const goButton=event.target.closest('[data-go]');if(goButton){showView(goButton.dataset.go);return}
    const riskButton=event.target.closest('[data-risk]');if(riskButton){riskFilter=riskButton.dataset.risk;$$('[data-risk]').forEach(node=>node.classList.toggle('selected',node===riskButton));renderPremarket();return}
    const symbolRow=event.target.closest('tr[data-symbol]');if(symbolRow){selectedSymbol=symbolRow.dataset.symbol;chartBars=[];chartLoadedAt=0;renderPremarket();return}
    const watch=event.target.closest('[data-watch]');if(watch){watch.disabled=true;await action(watch.dataset.remove==='1'?'/api/watch/remove':'/api/watch',{symbol:watch.dataset.watch},watch.dataset.remove==='1'?'已移出监测':'已加入监测并开始补齐数据');return}
    const kind=event.target.closest('[data-holding-kind]');if(kind){holdingKind=kind.dataset.holdingKind;renderHoldings();return}
    const edit=event.target.closest('[data-edit-holding]');if(edit){const row=workspace().holdings.real.find(item=>item.id===edit.dataset.editHolding);if(row)openHolding(row);return}
    const close=event.target.closest('[data-close]');if(close){$(`#${close.dataset.close}`).close();return}
    const connect=event.target.closest('[data-connect]');if(connect){connect.disabled=true;await action(`/api/connect/${connect.dataset.connect}`,{},'已开始检查连接');return}
    const read=event.target.closest('[data-alert-read]');if(read){await action('/api/alerts/read',{id:read.dataset.alertRead},'已标记为已读');return}
    const strategyButton=event.target.closest('[data-select-strategy]');if(strategyButton){selectedStrategy=strategyButton.dataset.selectStrategy;renderStrategyCenter();return}
    const strategyToggle=event.target.closest('[data-strategy-toggle]');if(strategyToggle){strategyToggle.disabled=true;await action(`/api/strategies/${strategyToggle.dataset.strategyToggle}/config`,{market:currentMarket,parameters:{},enabled:strategyToggle.dataset.enabled==='1',reason:strategyToggle.dataset.enabled==='1'?'重新启用策略':'手工停用策略'},'策略状态已生成新版本');return}
    const versions=event.target.closest('[data-show-versions]');if(versions){await openVersions(versions.dataset.showVersions);return}
    const rollback=event.target.closest('[data-rollback]');if(rollback){rollback.disabled=true;if(await action(`/api/strategies/${rollback.dataset.strategy}/rollback`,{market:currentMarket,version:rollback.dataset.rollback},'已恢复参数并生成新版本'))$('#versions-dialog').close();return}
    const analysisMonitor=event.target.closest('[data-analysis-monitor]');if(analysisMonitor&&!analysisResult?.monitored){if(await action('/api/analyze/add-monitoring',{symbol:analysisMonitor.dataset.analysisMonitor},'已加入持续监测')){analysisResult.monitored=true;renderAnalyze()}return}
    const saveAnalysis=event.target.closest('[data-analysis-save-holding]');if(saveAnalysis&&analysisResult){openHolding({symbol:analysisResult.symbol,name:analysisResult.name,source:'manual',quantity:Number($('#analyze-quantity').value)||'',cost:Number($('#analyze-cost').value)||'',entry_date:$('#analyze-date').value,stop:Number($('#analyze-stop').value)||null,target:Number($('#analyze-target').value)||null,note:'由单股分析录入'});return}
    if(event.target.id==='add-holding'){openHolding();return}
    if(event.target.id==='sync-holdings'){event.target.disabled=true;await action('/api/real-holdings/sync',{source:'all'},'持仓同步已完成或已保留上次有效结果');event.target.disabled=false;return}
    if(event.target.id==='refresh-premarket'){event.target.disabled=true;await action('/api/selection/prioritize',{market:currentMarket},'已优先更新当前市场盘前研究');return}
    if(event.target.id==='toggle-simulation'){await action('/api/settings',{...state.settings,simulation_enabled:!state.settings.simulation_enabled},state.settings.simulation_enabled?'已暂停模拟新开仓':'已恢复模拟新开仓');return}
    if(event.target.id==='benchmark'){await action('/api/benchmark',{},'已开始检查数据连接');return}
    if(event.target.id==='monitor-toggle'){await action('/api/monitor',{running:!state.monitor.running},state.monitor.running?'盯盘已暂停':'盯盘已恢复，正在重新核验行情');return}
    if(event.target.id==='save-notifications'){await action('/api/notifications',{enabled:$('#notify-enabled').checked,desktop:$('#notify-desktop').checked,sound:$('#notify-sound').checked},'提醒设置已保存');return}
    if(event.target.id==='test-notification'){await action('/api/notifications/test',{},'已提交测试通知，请查看Mac通知中心');return}
    if(event.target.id==='remove-holding'){const id=$('#holding-id').value;if(id&&await action('/api/real-holdings/remove',{id},'手工持仓记录已删除'))$('#holding-dialog').close();return}
    if(event.target.id==='run-replay'){const symbol=$('#replay-symbol').value;if(!symbol)return toast('当前市场没有可回放的监测股票');event.target.disabled=true;try{const result=await api('/api/replay',{symbol,source:'longbridge'});$('#replay-result').innerHTML=`<b>${esc(result.symbol)}</b> · ${result.evaluation_bars}根评估K线<br>${esc(result.label)}`;toast('回放完成')}catch(error){toast(error.message)}finally{event.target.disabled=false}return}
    if(event.target.id==='strategy-versions'){await openVersions(selectedStrategy);return}
  });
  $('#premarket-search').addEventListener('input',()=>state&&renderPremarket());
  $('#holding-form').addEventListener('submit',async event=>{event.preventDefault();const id=$('#holding-id').value,sourceValue=$('#holding-source').value,payload={id:id||null,symbol:$('#holding-symbol').value.trim().toUpperCase(),name:$('#holding-name').value.trim()||null,quantity:Number($('#holding-quantity').value),cost:Number($('#holding-cost').value),entry_date:$('#holding-date').value||null,stop:$('#holding-stop').value?Number($('#holding-stop').value):null,target:$('#holding-target').value?Number($('#holding-target').value):null,note:$('#holding-note').value.trim()};const path=id&&sourceValue!=='manual'?'/api/real-holdings/plan':'/api/real-holdings/manual';const body=path.endsWith('/plan')?{id,payload,entry_date:payload.entry_date,stop:payload.stop,target:payload.target,note:payload.note}:{...payload};delete body.payload;if(await action(path,body,'真实持仓计划已保存'))$('#holding-dialog').close()});
  $('#screen-form').addEventListener('submit',async event=>{event.preventDefault();const button=event.submitter;button.disabled=true;$('#screen-result').textContent='正在查询灵犀并筛出股票代码…';try{const result=await api('/api/screen',{query:$('#screen-query').value.trim()});$('#screen-result').innerHTML=`<p>${esc(result.text||'查询已完成')}</p>${(result.candidates||[]).map(row=>`<button class="secondary" data-watch="${esc(row.symbol)}">＋ ${esc(row.symbol)}</button>`).join('')}`;toast('灵犀查询完成')}catch(error){$('#screen-result').textContent=error.message;toast(error.message)}finally{button.disabled=false}});
  $('#settings-form').addEventListener('submit',async event=>{event.preventDefault();await action('/api/settings',{monitor_limit:Number($('#monitor-limit').value),simulation_enabled:state.settings.simulation_enabled,ib_port:Number($('#ib-port').value)},'运行设置已保存')});
  $('#strategy-workbench').addEventListener('submit',async event=>{if(event.target.id!=='strategy-config-form')return;event.preventDefault();const form=event.target,parameters={};form.querySelectorAll('[data-param]').forEach(input=>parameters[input.dataset.param]=input.value);const button=event.submitter;button.disabled=true;try{await api(`/api/strategies/${form.dataset.strategyId}/config`,{market:currentMarket,parameters,reason:$('#strategy-change-reason').value});toast('新参数版本已立即生效');await refresh()}catch(error){toast(error.message)}finally{button.disabled=false}});
  $('#analyze-form').addEventListener('submit',async event=>{event.preventDefault();const button=event.submitter;button.disabled=true;$('#analyze-result').innerHTML='<div class="empty">正在读取同源日线、五分钟K线、报价和盘口，并运行四种策略…</div>';const quantity=$('#analyze-quantity').value,cost=$('#analyze-cost').value;const holding=quantity&&cost?{quantity:Number(quantity),cost:Number(cost),entry_date:$('#analyze-date').value||null,available:$('#analyze-available').value?Number($('#analyze-available').value):null,stop:$('#analyze-stop').value?Number($('#analyze-stop').value):null,target:$('#analyze-target').value?Number($('#analyze-target').value):null}:null;try{analysisResult=await api('/api/analyze',{symbol:$('#analyze-symbol').value.trim().toUpperCase(),holding});if(analysisResult.market!==currentMarket)setMarket(analysisResult.market);const h=analysisResult.holding;if(h&&!holding){$('#analyze-quantity').value=h.quantity??'';$('#analyze-cost').value=h.cost??'';$('#analyze-date').value=h.entry_date||'';$('#analyze-available').value=h.available??'';$('#analyze-stop').value=h.stop??'';$('#analyze-target').value=h.target??''}renderAnalyze()}catch(error){analysisResult=null;$('#analyze-result').innerHTML=`<div class="empty">${esc(error.message)}</div>`;toast(error.message)}finally{button.disabled=false}});
  let lookupTimer;$('#analyze-symbol').addEventListener('input',event=>{clearTimeout(lookupTimer);lookupTimer=setTimeout(async()=>{const q=event.target.value.trim();if(q.length<2)return;try{const rows=await api('/api/lookup?q='+encodeURIComponent(q));$('#analyze-suggestions').innerHTML=rows.map(row=>`<option value="${esc(row.symbol)}">${esc(row.name)}</option>`).join('')}catch{}},220)});
}

async function openVersions(strategy){try{const rows=await api(`/api/strategies/${strategy}/versions?market=${currentMarket}`);$('#versions-title').textContent=`${strategyName(strategy)} · 参数历史`;$('#versions-content').innerHTML=rows.map((row,index)=>`<div class="version-row"><div><b>${esc(row.version)}</b><small>${esc(time(row.created_at))} · ${esc(row.reason)}</small>${row.replay?`<small>${esc(row.replay.label||'历史探索结果')} · ${esc(row.replay.message||row.replay.state)}</small>`:'<small>历史探索结果尚未运行</small>'}</div><span class="state-chip ${index===0?'buy':''}">${index===0?'当前版本':'历史版本'}</span>${index? `<button class="secondary" data-rollback="${esc(row.version)}" data-strategy="${esc(strategy)}">恢复此版</button>`:''}<details><summary>查看参数与差异</summary><pre>${esc(JSON.stringify(row.parameters,null,2))}</pre></details></div>`).join('');$('#versions-dialog').showModal()}catch(error){toast(error.message)}}

document.documentElement.dataset.market=currentMarket;showView(currentView);bindEvents();refresh();
try{const events=new EventSource('/api/events');events.onmessage=scheduleRefresh;events.onerror=()=>document.body.classList.add('disconnected')}catch{}
